---
title: "The Nuclear Arms Debate"
description: |
  An analysis on the nuclear arm debate as written Scott Sagan and Kenneth Waltz.
author:
  - name: Morgan Miller 
    url: https://example.com/norajones
    affiliation: The George Washington University
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Morgan Miller

Prof. Richard Chasdi

The George Washington University

03/13/21

The Question of Nuclear Arm Proliferation

The question of nuclear arms has been one that has not gone without debate. In recent decades the fear of a nuclear war has grown, as states attempt to maintain protection of their territory. These nuclear weapons create mass destruction, creating a high cost, low benefit situation. In analyzing this debate, I read *The Spread of Nuclear Weapons: A Debate Renewed*, written by Scott Sagan and Kenneth Waltz. This analysis provides insight on the pros and cons of nuclear proliferation. While my personal opinion leans towards Sagan's argument against nuclear proliferation, I found Waltz's argument of proliferation to be the most convincing. I believe this to be a result of a want for the world to be more predictable than it truly is; Humans crave predictability. However, there is no consistency or global police to hold all states accountable for their actions, international relations is an ever-changing concept.

To begin, I will analyze the realist arguments of Waltz, in which he states that "more nuclear arms may be better," (Waltz 3). The basis of this argument lies in the idea that nuclear weapons will be used to deter threats and therefore create less conflict and more peace. This can be seen between the United States and the Soviet Union during the Cold War. While this ideological battle had a focus on a nuclear arms race, they were never actually utilized and nuclear war was deterred. Waltz touches on the topic of nuclear arms in his report, "Why Iran Should Get the Bomb: Nuclear Balancing Would Mean Stability." This analysis claims that sanctions are unlikely to work against states, such as Iran. Therefore, the nuclear bomb would be a threat which could keep the state in line while creating stability. Waltz identifies that irrationality is at the forefront of the fears that lie within the idea of nuclear arms proliferation. He counters this fear by citing that all states want to survive and the use of nuclear weapons against another state in irrationality would endanger this survival. He writes, "Rulers want to have a country they can continue to rule," (Waltz 14) exemplifying the idea that states want to survive above all else. Another mentioned fear is terrorists being provided nuclear weapons. However, Waltz writes that history demonstrates that nuclear weapons discourage bold, dangerous decisions such as providing terrorists with nuclear arms as well as using them. When a state or group of actors has nuclear weapons, it is not long until they are a target of others due to the enhanced weaponry. It would be self-sabotage, Waltz argues, for a terrorist group to have nuclear arms when they would immediately become a threat and target to other states.

Waltz continues his analysis of nuclear arms by shining a light on the vertical nuclear proliferation of the global world, as opposed to a horizontal one. States who already have nuclear weapons are continuing to develop their arms. This proliferation is not spreading among all states, just growing in the ones who already have it. This leaves the states without nuclear arms at the mercy of those who do have them. Waltz acknowledges the fear of these less developed countries acquiring nuclear power. Yet, he also writes that there is no statistical evidence to back this fear up. Waltz addresses this fear in the quote, "What is required is that decisions be made that keep destruction within bounds..." (Waltz 15) which emphasizes the importance of nuclear weapons creating mass destruction. This means, to deter nuclear use, that states only need to be aware that using nuclear arms means they will be attacked as well. If anything, he argues, nuclear arms makes actors more cautious and the willingness of a state to use nuclear weapons is very small. This is due to the long-lasting effects of a nuclear war which would cause mass destruction, hurting all parties involved, and even those who were not. With the use of deterrence, nuclear power should not become a threat to the stability of the global world, but rather a helping hand. Waltz writes in the book, "The prediction is more important than the fact," (Waltz 34). This quote illustrates that a state may predict that their use of nuclear weapons will be met with other states' nuclear weapons in retaliation. The cost-benefit analysis of this situation proves the use of nuclear power as an offensive weapon to be too high a cost. In the case of a pre-emptive strike with nuclear weapons, one can see the high cost of nuclear war. In lecture, we spoke on the reasons behind a pre-emptive strike. It allows for first-strike advantage in a potentially inevitable war. To contradict these fears Waltz looks to the past, "Why should we expect new nuclear states to experience greater difficulties than the ones old nuclear states were able to cope with?" (Waltz 21). By looking at Waltz's argument, nuclear use would cause mass destruction for all which outweighs any potential benefits of being on the offensive. Nuclear weapons would be used in an emergency, last-resort option according to the realist theorist.

Sagan presents the opposite side of the nuclear debate. He declares that nuclear proliferation is not stable and should be avoided due to the lack of control in less civilized and developed states. The weaker institutions within these less developed states cannot handle the pressure of nuclear proliferation without serious consequences for the stability of the global world. While Sagan addresses the peaceful nuclear past in examples such as the Cold War, the narrow interests of the international world today makes for a fearful nuclear future. He claims that a pre-emptive war isn't as unlikely as Waltz makes it out to be. He writes, "Offensive doctrines enable military organizations to take the initiative," (Sagan 55) demonstrating that the acquisition of nuclear arms places power in the military. This can easily spiral into a "better now than later" (Sagan 55) mindset for a military trying to limit their losses and threats. Sagan illustrates the danger of nuclear power in the hands of the military by saying the military "... plan[s] incrementally, leading it to focus on immediate plans for war and not on the subsequent problems of managing the postwar world," (Sagan 55). This mindset would act as a motivation to use first-strike advantage in order to "anticipate and prevent" (Sagan 55) an attack from other states. While Waltz relies on actors to act rationally, Sagan believes there is no guarantee for this rationality. The military can become stuck in what Sagan calls "fuzzy thinking." He specifies that, with nuclear arms, the military is going to want to create invulnerable arms. Fuzzy thinking "can cause a state to spend billions of dollars building more forces than are necessary for rational deterrence," (Sagan 64). This means that the proliferation of nuclear arms, and subsequently more power in the military with these weapons, would create a highly militarized, unstable state and global world. The argument of irrationality made by Sagan continues as he refers to the nuclear arms race as a "deadly cat and mouse game," (Sagan 72). While Waltz's realist views believe there will be rational thinking with nuclear arms, Sagan says this is not necessarily true. There are a plethora of goals and political motives which may cause instability from the proliferation of nuclear weapons. Specifically, Sagan cites the dangers of "accidental or unauthorized use," (Sagan 72). Organizations are limited in their rationality depending on the situation, which Sagan describes as bounded rationality. Sagan speaks about rationality saying, "My theory makes less heroic assumptions about the rationality of states," (Sagan 83). There is no way to predict an irrational or rational behavior of a state, and it only takes one reckless state to cause global instability.

While Sagan acknowledges that there are back-up systems to prevent the use of nuclear weapons from becoming weapons of mass destruction, he says these systems are redundant. "Redundancy makes the system both more complex and more opaque," (Sagan 74) leaving space for accidents and unauthorized use of nuclear weapons. Mistakes are not avoidable, but the "politics of blame" (Sagan 75) is what Sagan cites as the main issue here. There is a lack of learning from mistakes in the global world. While there may have been no mass destruction with nuclear arms in the past, there have been near-accidents. Even though these did not cause disaster, they pose a threat to the future of a peaceful global world in which stability will be harder to maintain. Sagan sheds light on six reasons why states will have more instability with nuclear arms than states in the past: organizational issues and a lack of financial resources, opaqueness of the nuclear international world, the tight-coupling problem, decapitation attacks, political and social unrest, and accidental detonations (Sagan 78). Of these reasons, Sagan developed the arguments of tight-coupling and decapitation attacks in support of his claim. The tight-coupling issue addresses that the new states who would develop nuclear arms are in much closer proximity to each other than states in the past, such as the United States and the Soviet Union. This plays an important role in understanding the increased tensions in future nuclear arms proliferation. In addition, the decapitation attack, an attack at the central government, is evidence for the dangers of nuclear arms proliferation. Out of fear of a decapitation attack, a government may create a pre-delegation policy which extends nuclear power to lower-level personnel in the military, making nuclear war and accidental detonations more likely. Sagan writes on the realist perspective of state behavior saying, "The nuclear optimists' view... is based on a rationalist assumption that the behavior of new nuclear states will reflect their interests in avoiding nuclear war," (Sagan 83). While war may be costly, Sagan demonstrates why rational actions of states cannot be assumed. He ends his main arguments by giving U.S. policy suggestions and states that the U.S. should implement more "intellectual persuasion" instead of sanctions and other forms of restriction. In addition, the U.S. should cooperate with other nuclear states and share information to create more stability and free flowing information in the global world to help the issue of misinformation and incorrect assumptions.

Continuing his analysis of nuclear arms, Sagan's report, "The Perils of Proliferation in South Asia," sheds light on his views of nuclear proliferation. In this text Sagan writes, "... nuclear weapons are controlled by military organizations and civilian bureaucracies, not by states or by statesmen." This quote illustrates that for Sagan, the issue is less about irrationality, and more on accidental or unauthorized use as stated prior. This analysis looks directly at the example of Pakistan and India for guidance as he proves that the real danger of nuclear arms proliferation cannot be predicted.

Through both analyses of nuclear arms proliferation, there are multiple ties to lecture and the concepts we have heavily emphasized in our study of international relations. Firstly, the importance of cost-benefit analysis. Mutually assured destruction would be a direct effect of nuclear war, leaving costs for all states. In analyzing the cost of using nuclear arms in the global world, one can see that it would not be in the favor of a state to use them, unless there was no other option of deterrence. This defends the stance of Waltz in providing evidence for why nuclear proliferation would not mean inevitable war. Nevertheless, unpredictability and uncertainty are two defining characteristics of the global world. In Arnold Wolfers' article, "National Security As An Ambiguous Symbol", he writes on the impossibility of interpreting a state's intentions with absolute certainty. Wolfers brings in the idea of the security dilemma, when increasing your defense effectively decreases it as well. This relates to nuclear arms in the way that in such an ambiguous international world, there is no way to know how states would use nuclear arms and if it would create global stability or instability. This supports Sagan's claim that proliferation would cause instability, but the ambiguity does not rule out the argument of Waltz. Phil Williams also reflects this idea through his piece on mistrust and misinformation in the global world, "Lawlessness and Disorder: An Emerging Paradigm for the 21st Century." The unpredictable foreign interactions directly creates global instability, and therefore, in the case of nuclear arms, there is no clear way to tell how interactions would change the dangers of nuclear proliferation, which supports the argument of Sagan. In continuance of this argument, as written in "Society and Anarchy In International Relations" by Hedley Bull, predictability is not the reality of the global world. There is misinformation and incorrect assumptions made by states which affect how they interact with others in the global world. By adding nuclear arms into this discussion, one can see that the stakes are much higher for mass destruction when interactions in the global world are already unpredictable and arguably unstable. In looking at a case such as North Korea, the foreign interactions between their government and the majority of other states is unstable, begging the question: do we want these deadly weapons in the hands of unpredictable leaders? However, the anarchy present in the global world does not prove to be an answer for potential nuclear war resulting from proliferation. As spoken of in lecture, anarchy does not explain why war occurs, but rather only explains security development. Waltz's realism addresses that the global world is characterized by anarchy, but counters this with the idea that the most important actor is the state. The state, from this theory, provides security, identity, and is a legit institution. This provides a foundation to Waltz's declaration that nuclear arms would cause stability. Finally, the debate of nuclear proliferation cannot be had without bringing in the importance of geography and proximity of states as spoken of in Sagan's portion of the book. The stability of a country's nuclear arms lies in whether they have isolation, and therefore geographical buffers, or not. A state will feel less vulnerable with isolation and therefore less likely to make rash decisions which would create instability in nuclear arms proliferation. These states, as mentioned in lecture, score higher on the passive invulnerability scale, such as the United States.

In conclusion, I believe the book, The Spread of Nuclear Weapons: A Debate Renewed written by Scott Sagan and Kenneth Waltz, is a great analysis of the pros and cons of nuclear proliferation in the future global world. While both authors took very different stances on the issue at hand, they both made points which emphasized the role of the states, military, and rational decision-making. This analysis sheds light on the human want for predictability in the global world, and the ability to believe in rational-decision making by state leaders. Yet, it also addresses the inconsistencies in these optimistic beliefs. This book is a must-read for all developing hypotheses about the proliferation of nuclear arms, and provides an in-depth debate on the intricacies of the nuclear world.

Bibliography

Bull H. (1995) "Society and Anarchy in International Relations" (1966). In: Der Derian J. (eds) International Theory. Palgrave Macmillan, London. <https://doi.org/10.1007/978-1-349-23773-9_5>

Sagan, Scott D. Stanford University, 2001, The Perils of Proliferation in South Asia, web.stanford.edu/class/polisci243b/readings/sagan.pdf.

Sagan, Scott D., and Kenneth N. Waltz. The Spread of Nuclear Weapons: a Debate Renewed (Second Edition). W.W. Norton & Co, 2003.

Waltz, Kenneth N. "Why Iran Should Get the Bomb: Nuclear Balancing Would Mean Stability." Foreign Affairs, vol. 91, no. 4, 2012, pp. 2--5. JSTOR, www.jstor.org/stable/23218033. Accessed 9 Mar. 2021.

Williams, Phil. "Lawlessness and Disorder: An Emerging Paradigm for the 21st Century." In: Miklaucic, Michael, and Jacqueline Brewer. Convergence : Illicit Networks and National Security In the Age of Globalization.

Wolfers, Arnold. "'National Security' as an Ambiguous Symbol." Political Science Quarterly, vol. 67, no. 4, 1952, pp. 481--502. JSTOR, www.jstor.org/stable/2145138. Accessed 9 Mar. 2021.
